export const CATEGORIES = [
  { name: 'All',                emoji: '🏪' },
  { name: 'Fruits & Vegetables',emoji: '🥦' },
  { name: 'Dairy & Eggs',       emoji: '🥛' },
  { name: 'Snacks',             emoji: '🍿' },
  { name: 'Beverages',          emoji: '🧃' },
  { name: 'Grains & Staples',   emoji: '🌾' },
  { name: 'Bakery',             emoji: '🍞' },
  { name: 'Oils & Condiments',  emoji: '🫙' },
  { name: 'Personal Care',      emoji: '🧴' },
  { name: 'Household',          emoji: '🧹' },
  { name: 'Frozen & Ready',     emoji: '❄️' },
  { name: 'Baby & Kids',        emoji: '👶' },
  { name: 'Pet Care',           emoji: '🐾' },
]

export const PRODUCTS = [
  { id:1,  name:'Fresh Tomatoes',    qty:'500g',   price:29,  mrp:40,  discount:28, emoji:'🍅', cat:'Fruits & Vegetables' },
  { id:2,  name:'Bananas',           qty:'6 pcs',  price:39,  mrp:50,  discount:22, emoji:'🍌', cat:'Fruits & Vegetables' },
  { id:3,  name:'Spinach',           qty:'250g',   price:19,  mrp:25,  discount:24, emoji:'🥬', cat:'Fruits & Vegetables' },
  { id:4,  name:'Onions',            qty:'1 kg',   price:35,  mrp:45,  discount:22, emoji:'🧅', cat:'Fruits & Vegetables' },
  { id:5,  name:'Potatoes',          qty:'1 kg',   price:29,  mrp:35,  discount:17, emoji:'🥔', cat:'Fruits & Vegetables' },
  { id:6,  name:'Carrots',           qty:'500g',   price:35,  mrp:45,  discount:22, emoji:'🥕', cat:'Fruits & Vegetables' },
  { id:7,  name:'Apples',            qty:'4 pcs',  price:89,  mrp:110, discount:19, emoji:'🍎', cat:'Fruits & Vegetables' },
  { id:8,  name:'Amul Milk',         qty:'500ml',  price:30,  mrp:32,  discount:6,  emoji:'🥛', cat:'Dairy & Eggs' },
  { id:9,  name:'Eggs',              qty:'12 pcs', price:79,  mrp:90,  discount:12, emoji:'🥚', cat:'Dairy & Eggs' },
  { id:10, name:'Amul Butter',       qty:'100g',   price:55,  mrp:62,  discount:11, emoji:'🧈', cat:'Dairy & Eggs' },
  { id:11, name:'Paneer',            qty:'200g',   price:75,  mrp:90,  discount:17, emoji:'🧀', cat:'Dairy & Eggs' },
  { id:12, name:'Curd',              qty:'400g',   price:45,  mrp:52,  discount:13, emoji:'🫙', cat:'Dairy & Eggs' },
  { id:13, name:"Lay's Chips",       qty:'52g',    price:20,  mrp:20,  discount:0,  emoji:'🥔', cat:'Snacks' },
  { id:14, name:'Marie Biscuits',    qty:'150g',   price:30,  mrp:35,  discount:14, emoji:'🍪', cat:'Snacks' },
  { id:15, name:'Namkeen Mix',       qty:'200g',   price:45,  mrp:55,  discount:18, emoji:'🫙', cat:'Snacks' },
  { id:16, name:'Popcorn',           qty:'100g',   price:60,  mrp:75,  discount:20, emoji:'🍿', cat:'Snacks' },
  { id:17, name:'Coca Cola',         qty:'750ml',  price:45,  mrp:50,  discount:10, emoji:'🥤', cat:'Beverages' },
  { id:18, name:'Mango Juice',       qty:'1L',     price:89,  mrp:110, discount:19, emoji:'🧃', cat:'Beverages' },
  { id:19, name:'Green Tea',         qty:'25 bags',price:99,  mrp:120, discount:18, emoji:'🍵', cat:'Beverages' },
  { id:20, name:'Coffee Powder',     qty:'200g',   price:149, mrp:180, discount:17, emoji:'☕', cat:'Beverages' },
  { id:21, name:'Basmati Rice',      qty:'1 kg',   price:89,  mrp:100, discount:11, emoji:'🍚', cat:'Grains & Staples' },
  { id:22, name:'Toor Dal',          qty:'500g',   price:65,  mrp:80,  discount:19, emoji:'🫘', cat:'Grains & Staples' },
  { id:23, name:'Wheat Atta',        qty:'5 kg',   price:249, mrp:290, discount:14, emoji:'🌾', cat:'Grains & Staples' },
  { id:24, name:'Poha',              qty:'500g',   price:39,  mrp:50,  discount:22, emoji:'🍛', cat:'Grains & Staples' },
  { id:25, name:'White Bread',       qty:'400g',   price:45,  mrp:50,  discount:10, emoji:'🍞', cat:'Bakery' },
  { id:26, name:'Croissant',         qty:'4 pcs',  price:79,  mrp:90,  discount:12, emoji:'🥐', cat:'Bakery' },
  { id:27, name:'Sunflower Oil',     qty:'1L',     price:139, mrp:160, discount:13, emoji:'🫙', cat:'Oils & Condiments' },
  { id:28, name:'Tomato Ketchup',    qty:'500g',   price:89,  mrp:105, discount:15, emoji:'🍅', cat:'Oils & Condiments' },
  { id:29, name:'Shampoo',           qty:'200ml',  price:149, mrp:180, discount:17, emoji:'🧴', cat:'Personal Care' },
  { id:30, name:'Soap Bar',          qty:'3 pcs',  price:79,  mrp:90,  discount:12, emoji:'🧼', cat:'Personal Care' },
  { id:31, name:'Toothpaste',        qty:'150g',   price:69,  mrp:80,  discount:14, emoji:'🦷', cat:'Personal Care' },
  { id:32, name:'Floor Cleaner',     qty:'1L',     price:99,  mrp:120, discount:18, emoji:'🧹', cat:'Household' },
  { id:33, name:'Dish Wash Gel',     qty:'500ml',  price:65,  mrp:80,  discount:19, emoji:'🫧', cat:'Household' },
  { id:34, name:'Frozen Peas',       qty:'500g',   price:69,  mrp:80,  discount:14, emoji:'🟢', cat:'Frozen & Ready' },
  { id:35, name:'Frozen Fries',      qty:'400g',   price:99,  mrp:120, discount:18, emoji:'🍟', cat:'Frozen & Ready' },
  { id:36, name:'Baby Cereal',       qty:'300g',   price:199, mrp:225, discount:12, emoji:'🍼', cat:'Baby & Kids' },
  { id:37, name:'Dog Food',          qty:'1 kg',   price:299, mrp:350, discount:15, emoji:'🐕', cat:'Pet Care' },
]